### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by LenkonN** [LenkonN/OsuStoryboardConstructor#1]
------------
### To-do list
_(In order of priority)_

------------
- [ ]     **[ IN PROCCESS ] :**

- [x] | Rotate and Scale
- [x] | Re-create timeline system
- [x] | Re-create timeline system (Again)
- [ ] | Create animation key structure
- [ ] | Displaying keys on the timeline
- [x] | Create sprite object
- [ ] | Once an object is created, it is selected by itself
- [x] | Once an object is deleted, the previous object in the list is selected
- [x] | Add more sumary in code

------------
- [ ]     **[ IN PLANS ] :**

- [ ] | Create particle system object
- [ ] | Change all Icons
- [ ] | Add icons for all object in tree
- [ ] | Fix drag

------------
- [ ]     **[ IN IDEAS ] :** 

- [ ] | Сreate documentation on the use of the program
- [ ] | System of visual customization of editor
- [ ] | Markers for timeline
- [ ] | Add localization for several languages (currently there are people for: Russian, Spanish)
- [ ] | Discord integration
- [ ] | Easing system
- [ ] | Add statistics
- [ ] | Taiko line object
- [ ] | Export .osb to json project
- [ ] | Text editor
- [ ] | Magnetic grid
- [ ] | Trigger object (When a key-command is executed, it interacts with all items within itself. For example, moving)
- [ ] | Text object with text-to-image conversion system
- [ ] | Animation object (The ability to create actions, and will repeat that action as its behavior has been configured)
- [ ] | Log file
- [ ] | Reading data from an .osu file
- [ ] | Interaction with several objects at the same time (Probably partial?)
- [ ] | Saving to a separate file and loading object parameters
- [ ] | Component system
- [ ] | Component "Script"
- [ ] | Component "Outline"
- [ ] | Optimizing the reading of a json project file (Save it in a thread rather than open/close it?)
- [ ] | Support for collaborative development of the storyboard. (In fact, in the very-very-very distant plans, I won't think about it for at least half a year or year after the release)

------------
- [x]     **[ DONE ] :**

- [x] | Add system messages
- [x] | Fix disclosure of all groups after any interaction with object
- [x] | Moving objects within the object tree
- [x] | Create "Attribute" field in json project file, which will contain unique parameters for the object. (For example for sprite, it's position, rotate and scale)
- [x] | Create basic structure
